### ISSUE TITLE
v0.5

### ISSUE THREAD

**Issue by axilleas** [librenet/ansible#37]
New server, bigger update. Getting ready Diaspora 0.5.1. This is a list of tasks that need to be addressed.

- [ ] New role: camo proxy (#13)
- [ ] New role: [prosody xmpp server](https://wiki.diasporafoundation.org/Integration/XMPP/Prosody)
- [ ] New role: SELinux (#26)
- [ ] New role sshd (#17)
- [x] [`diaspora.yml` new options](https://github.com/diaspora/diaspora/blob/master/config/diaspora.yml.example)
- [x] Revert `routes.rb` to match upstream and ->
- [ ] Configure new [splash page](https://wiki.diasporafoundation.org/Custom_splash_page)
- [ ] Nginx include camo

**Comment by axilleas** [comment]
Closed in favor of #38
